name: Deploy Vite Logistica 2026

on:
  push:
    branches: ["main"]    # deploy automático quando mudar o main
  workflow_dispatch:       # habilita o botão "Run workflow"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Build do Vite
        run: npm run build

      - name: Upload artefato para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy para GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
